### ISSUE TITLE
Shared folders

### ISSUE THREAD

**Issue by StevenP94** [minnyres/docker-amule-dlp#2]
Hi, there is a way to add shared folders?
I have folders on other disks than /downloads.
thanks in advance

**Comment by minnyres** [comment]
Hi. If I understand correctly, you need to share files in multiple directories, e.g. `/disk1`, `/home/user/disk2`, `/mnt/disk3`, and these directories are on different disks.

If you are using Linux, a workaround is to use [bind mount](https://unix.stackexchange.com/questions/198590/what-is-a-bind-mount) so that these directories can be placed in the same path.
First, create directories to bind folders
```
mkdir -p <downloads>/disk1
mkdir -p <downloads>/disk2
mkdir -p <downloads>/disk3
```
where `<downloads>` is the shared file path for [docker-compose](https://github.com/minnyres/docker-amule-dlp#docker-compose).
Then, you can bind the shared folders to this path:
```
sudo mount --bind /disk1 <downloads>/disk1
sudo mount --bind /home/user/disk2 <downloads>/disk2
sudo mount --bind /mnt/disk3 <downloads>/disk3
```

**Comment by StevenP94** [comment]
Thanks a lot for your reply, I made some attempts using symlink with no result, now I'll try your approach. Thanks again for your attention.
